[versions]
junit = "4.13.2"
kotlin = "1.9.24"
nanojson = "1.9"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
nanojson = { module = "com.grack:nanojson", version.ref = "nanojson" }

[plugins]
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
